name: copy_class_quota

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  copy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - url: 'https://w5.ab.ust.hk/wcq/cgi-bin/2320/'
            dir: 'class_quota'
    steps:
      - uses: actions/checkout@v2
      - name: Install httrack etc.
        run: sudo sh setup.sh
      - run: sh copy.sh ${{matrix.url}} ${{matrix.dir}}
