name: copy_luanboshiysclub

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: 45 0-23/6 * * *

permissions:
  contents: write

jobs:
  copy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - url: 'http://luanboshiysclub.com/'
            dir: 'luanboshiysclub'
    steps:
      - name: Install httrack
        run: sudo apt-get install -y httrack
      - uses: actions/checkout@v2
      - run: sh copy.sh ${{matrix.url}} ${{matrix.dir}}
