name: copy_class_quota

on:
  push:
    branches: ["**"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write

jobs:
  copy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - url: 'https://w5.ab.ust.hk/wcq/cgi-bin/2320/'
            dir: 'class_quota'
    steps:
      - name: Install httrack
        run: sudo apt-get install -y httrack
      - uses: actions/checkout@v2
      - run: sh copy.sh ${{matrix.url}} ${{matrix.dir}}
